config/routes.rb
SchoolSolutions::Application.routes.draw do

  resources :contacts

  

  match '/contact', :to => 'contacts#new'
 
 resources :users
  match '/new', :to => 'users#new'

  match '/about', :to => 'pages#about'
  match '/services', :to => 'pages#services'
  match '/products', :to => 'pages#products'
  
resources :sessions, :only => [:new, :create, :destroy]
match '/signup', :to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'

  root :to => 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :name, :presence =>true,
				 :length =>{ :maximum => 50}
validates :email, :presence => true,
				  :format =>{ :with => email_regex}
validates :organisation, :presence =>true,
				 :length =>{ :maximum => 50}
validates :enquiry, :presence =>true,
				 :length =>{ :maximum => 1000}


end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password
attr_accessible :name, :email,:password, :password_confirmation
email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :name, :presence =>true,
                 :length =>{ :maximum => 50}
validates :email, :presence => true,
                  :format =>{ :with => email_regex},
				  :uniqueness => { :case_sensitive => false} 

validates :password, :presence => true,
:confirmation => true,
:length => { :within => 6..40 }
before_save :encrypt_password

def has_password?(submitted_password)
encrypted_password == encrypt(submitted_password)
end

def self.authenticate(email, submitted_password)
user = find_by_email(email)
return nil if user.nil?
return user if user.has_password?(submitted_password)
end

def self.authenticate_with_salt(id, cookie_salt)
user = find_by_id(id)
(user && user.salt == cookie_salt) ? user : nil
end

private
def encrypt_password
self.salt = make_salt if new_record?
self.encrypted_password = encrypt(password)
end
def encrypt(string)
secure_hash("#{salt}--#{string}")
end
def make_salt
secure_hash("#{Time.now.utc}--#{password}")
end
def secure_hash(string)
Digest::SHA2.hexdigest(string)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
before_filter :admin_user, :only => :destroy
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    
      if @contact.save
         redirect_to @contact
         flash[:success]='Thank you for your enquiry.We will get back to you within 24 hours.' 
        
      else
      render action: "new"
      end
    end
 

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

      if @contact.update_attributes(params[:contact])
       redirect_to @contact
       flash[:success]='Information was successfully updated.' 
    
      else
       render action: "edit" 
       render json: @contact.errors, status: :unprocessable_entity 
      end
    end
  
  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
  private
def authenticate
deny_access unless signed_in?
end
def correct_user
@user = User.find(params[:id])
redirect_to(root_path) unless current_user?(@user)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
@title="Home"
  end

def about
  @title="About us"
  end
  
  

  def products
  @title="Products"
  end

  def services
  @title="Services"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.authenticate(params[:session][:email],
params[:session][:password])
if user.nil?
flash.now[:error] = "Invalid email/password combination."
@title = "Sign in"
render 'new'
else
sign_in user
redirect_back_or user
end
end

  def destroy
  sign_out
redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
before_filter :correct_user, :only => [:edit, :update]
before_filter :admin_user, :only => :destroy


  def new
  @user = User.new
  @title="new admin"
  end
  
 def create
@user = User.new(params[:user])
if @user.save
sign_in @user
flash[:success] = "Welcome to the SSK!"
redirect_to @user
else
@title = "Sign up"
render 'new'
end
end

def update
@user = User.find(params[:id])
if @user.update_attributes(params[:user])
flash[:success] = "Profile updated."
redirect_to @user
else
@title = "Edit user"
render 'edit'
end
end

def index
@title="All users"
@users=User.all
end

  def show
  @user=User.find(params[:id])
  @title=@user.name
  end
  
  def edit
  @title="Edit user"
  end
  
  private
def authenticate
deny_access unless signed_in?
end
def correct_user
@user = User.find(params[:id])
redirect_to(root_path) unless current_user?(@user)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
# Return a title on a per-page basis.
def title
base_title = "SchoolSolutionsKenya"
if @title.nil?
base_title
else
"#{base_title} | #{@title}"
end
end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def sign_in(user)
cookies.permanent.signed[:remember_token] = [user.id, user.salt]
current_user = user
end

def current_user=(user)
@current_user = user
end

def current_user
@current_user ||= user_from_remember_token
end
def current_user?(user)
user == current_user
end
def deny_access
store_location
redirect_to signin_path, :notice => "Please sign in to access this page."
end
def signed_in?
!current_user.nil?
end
def redirect_back_or(default)
redirect_to(session[:return_to] || default)
clear_return_to
end
def sign_out
cookies.delete(:remember_token)
current_user = nil
end

private
def user_from_remember_token
User.authenticate_with_salt(*remember_token)
end
def remember_token
cookies.signed[:remember_token] || [nil, nil]
end
def store_location
session[:return_to] = request.fullpath
end
def clear_return_to
session[:return_to] = nil
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this enquiry from being submitted:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :organisation %><br />
    <%= f.text_field :organisation %>
  </div>
  <div class="field">
    <%= f.label :enquiry %><br />
    <%= f.text_area :enquiry %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Organisation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.organisation %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
An SSK's representative is always ready to answer your call or email. If you need support or just have an enquiry, do not hesitate to contact us.
<br><b>Telephone</b>
+254 722 143 782
<br><b>E-mail</b>
info@ssk.com
<p>You could as well fill this simple form and we will get back to you in no time.
<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Organisation:</b>
  <%= @contact.organisation %>
</p>


</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_footer.html.erb
<div id="footer">
<% if signed_in? %>
<%= link_to "Profile", current_user %>
<%= link_to "Settings", edit_user_path(current_user) %>
<%= link_to "Users", users_path %>
<%= link_to "Sign out", signout_path, :method => :delete %>
<% else %>
<%= link_to "Sign in", signin_path %>
<% end %>
<%= link_to "Careers at SSK", '#' %>
<%= link_to "Products", products_path %>
<%= link_to "Services", services_path %>
<%= link_to "Contact us", new_contact_path %>
SchoolSolutionsKenya(SSK) &copy; 2012 | All Rights Reserved 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= title %></title>
<%= csrf_meta_tag %>
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= javascript_include_tag :defaults %>
</head>
<body>
<div class="container">
<header>
<div id="topright">

<br><br><font color="#F7CB33" >Excellence.</font><font color="#5C3317">Creativity.</font><font color ="#6CC417">Performance</font>

</div>

<div id="top">
<%= image_tag("/assets/logo.JPG", :alt => "SchoolSolutions", :id => "gallery") %>
<h1>SchoolSolutionsKenya</h1>
<p align="center">www.schoolsolutionskenya.com</p>
</div>
<%= image_tag("/assets/1.jpg", :alt => "SchoolSolutions", :id => "gallery") %><%= image_tag("2.jpg", :alt => "SchoolSolutions", :id => "gallery") %><%= image_tag("3.jpg", :alt => "SchoolSolutions", :id => "gallery") %>
</header>
<section class ="round">
<div id="content">
<div id="menu">
<%= link_to "Home", root_path %>
<%= link_to "Products/Services", products_path %>
<%= link_to "Careers", services_path %>
<%= link_to "Contact us", new_contact_path %>
</div>
<div id="pad">
      <p>&nbsp;</p>
      <% flash.each do |key, value| %>
<div class="flash <%= key %>"><%= value %></div>
<% end %>
      <%= yield %>
         
      </div>
  </div>
<div id="news">
  <h1><font color="#5C3317">Quick Reads</font></h1>
<ul>
<li><%= link_to "Why should your school have website?", '#' %></li>
<li><%= link_to "Why should your school have a school management system?", '#' %></li>
<li><%= link_to "Why products and services do we offer?", '#' %></li>
<li><%= link_to "Why should embrace ICT?", '#' %></li>
</ul>
<h1><font color="#5C3317">Quick Links</font></h1>
<ul>
<li><%= link_to "About SSK", '#' %></li>
<li><%= link_to "Products", '#' %></li>
<li><%= link_to "Services", '#' %></li>
<li><%= link_to "Contact us", '#' %></li>
<li><%= link_to "Careers at SSK", '#' %></li>
<li><%= link_to "Legal notice", '#' %></li>
  </ul>
  </div>
  </section>
<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About SchoolSolutionsKenya(SSK)</h1>
<p>SchoolSolutionsKenya is a technological company dedicated to serving schools, colleges,universities and other learning innstitutions in Kenya. We are the only company which solely specialises in providing customised solutions to learning institutions in Kenya. 
Some of the products and services we specialise in are:
<ul>
<li>Websites</li>
<li>School Management Systems</li>
<li>Hardware such as computers, printers, scanners and photocopiers</li>
<li>Networking solutions</li>
</ul>
So how do we maintain our reputation as the best such company in Kenya? The first reason is that we do not compromise on quality and standards. Everything is done to perfection. Our staff are skilled developers who are committed to churning out great solutions all the time. <br>The second reason is that we are very affordable. This we can promise you. No other company will provide quality of the highest standards at our prices. And we believe that you should find out about this. Indeed, we will work with your budget! You got budgetary constraints? Don't worry. We will still sort you out! Contact us today to find out even more about our unbelievable offers</p>

app/views/pages/home.html.erb
<h3><font color="#5C3317" size="5px" ><b>Welcome to a world of <i>brilliance</i></font></b></h3>
We here at SchoolSolutionsKenya&#0153 are dedicated to providing exemplary solutions to all schools and learning institutions in Kenya. We will put your institution online in no time, as well as providing school management software of the highest quality. We are also committed to supplying all your hardware needs such as computers,networking hardware, servers, printers, scanners, photocopiers etc.
<%= link_to "Visit our products/services page for more information.", products_path %>
The four key areas we focus on are:
<ul>
<b>
<font color="#6CC417" >
<li>Strategic Consultation</li>
<li>Infrastructure Solutions</li>
<li>Software + Services</li>
<li>Professional Support</li>
</font>
</b>
</ul>

Being the sole ICT solutions company in Kenya that is dedicated to learning institutions, we are in the best position to solve all your problems. We are driven by a strong desire to see schools in Kenya adopt ICT to streamline their activities and improve the quality of education offered.
<ul>
<font color ="#000">
<li>We will set up a fully functional website for your school in the shortest time possible!</li>
<li>Our school management software will automate your school and save upto 40% of your operational costs.  </li>
<li>All our products and services are of the highest quality and are unbelievably affordable!</li>
<li>We are committed to Excellence, Creativity and Performance</li>
</font>
</ul>

Contact us now to find out to experience the difference.<%= link_to "We think you should.", new_contact_path %>

app/views/pages/products.html.erb
<h4><font color="#6CC417" size="4px">Software and Services</font></h4>
We ensure that we deliver quality, secure and reliable software. From school management systems, exciting websites as well as other proprietary and opensource solutions, we make sure that we achieve our core values of excellence, creativity and performance. Contact us to find out what is best for you.
<h4><font color="#6CC417" size="4px">Infrastructure Solutions</font></h4>
Your institution needs tailor-made solutions to enhance maximum productivity. Our company caters for all your needs ranging from storage, operating environments, network optimisation and much more. We specialise on proprietary as well as open source solutions, security management,virtualisation strategies and networking issues. We will guide you through every step of the way to make sure that you reap maximum returns for your investment.
<h4><font color="#6CC417" size="4px">Strategic Consultation</font></h4>
We provide the very best guidance and advice to our clients concerning all ICT issues. From troubleshooting, installation of new technologies, design issues, implementing an IT strategy, best practices, disaster management-you name it: we will have it sorted for you.
<h4><font color="#6CC417" size="4px">Professional Support</font></h4>
SchoolSolutionsKenya prides itself in providing efficient customer service. We therefore go the extra mile to optimise your systems by providing on-site staff and remote support. Our clients can request a remote call or any form of assistance by contacting us on:
<br>Tel: +254 722 143 782

app/views/pages/services.html.erb
SchoolSolutionsKenya is an ambitious company. This ambition means that exciting opportunities will always be available for equally ambitious individuals. Consequently, we are always on the lookout for talented, self-driven and hardworking individuals who are willing and able to work in a team-based environment.
<br><br>If you are excited about IT, please send us your CV accompanied by responses to these questions below?
<ul>
<li> Why would you love to work for us?</li>
<li>How did you know about SchoolSolutionsKenya?</li>
<li>What is your area of specialisation in IT?</li>
<li>Do you have any experience in any area of IT?</li>
<li>Do you have any portfolio of your work?</li>
</ul>
<p>Send us your c.v to <mail>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %><div id="error_explanation"><h2><%= pluralize(object.errors.count, "error") %>prohibited this <%= object.class.to_s.underscore.humanize.downcase %>from being saved:</h2><p>There were problems with the following fields:</p><ul><% object.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %></ul></div><% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1><%= form_for(@user) do |f| %><%= render 'shared/error_messages', :object => f.object %><div class="field"><%= f.label :name %><br /><%= f.text_field :name %></div><div class="field"><%= f.label :email %><br /><%= f.text_field :email %></div><div class="field"><%= f.label :password %><br /><%= f.password_field :password %></div><div class="field"><%= f.label :password_confirmation, "Confirmation" %><br /><%= f.password_field :password_confirmation %></div><div class="actions"><%= f.submit "Update" %></div><% end %>

app/views/users/index.html.erb
<h1>All users</h1><ul class="users"><% @users.each do |user| %><%= link_to user.name, user %><% if current_user.admin? %>| <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",:title => "Delete #{user.name}" %><% end %><% end %></ul>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>